name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  unittests:
    name: Go Unittests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download
      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.25.0
        #  go get -u github.com/ory/go-acc
        shell: bash

      - name: Setup Build
        run: |
          go generate
          go build
        shell: bash

      - name: Lint
        run: golangci-lint run --verbose --config test/.golangci.yml --enable gofmt --enable goimports
        if: matrix.os != 'windows-latest'
      - name: Lint Windows
        run: golangci-lint run --verbose --config test/.golangci.yml
        if: matrix.os == 'windows-latest'

#      - name: Test
#        run: go-acc ./...
#      - name: Upload coverage
#        env:
#          CI: "true"
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#        run: bash <(curl -s https://codecov.io/bash) -f coverage.txt
#        # if: matrix.os == 'windows-latest'
#        shell: bash

  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install astilectron-bundler
        run: go get -u github.com/asticode/go-astilectron-bundler/...

      - run: yarn build
      - run: astilectron-bundler
        working-directory: app

      - name: Upload elementary-ui
        uses: actions/upload-artifact@master
        with:
          name: elementary-ui ${{ matrix.os }}
          path: app/output
